title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 You can update description in update blog details page.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://justinechacko.github.io/testac" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Your awesome title

date: 2018-03-08 08:16:46 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: https://justinechacko.github.io/testac/
google_analytics: UA-31XXXXXX-X
gems: [jekyll-paginate]
cover: 
author_image: 
# Details for the RSS feed generator
author:        testac
